# Generated by Django 4.1.2 on 2022-10-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajay', '0002_rename_update_about_updated_alter_home_greetings1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skils_name',
            new_name='skill_name',
        ),
    ]
