# Generated by Django 4.1.2 on 2022-10-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajay', '0003_rename_skils_name_skills_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_no', models.IntegerField(max_length=12)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
