# Generated by Django 4.1.2 on 2022-10-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajay', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
