# Generated by Django 4.1.2 on 2022-10-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajay', '0005_alter_contact_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='picture',
        ),
    ]
